# Generated by Django 5.0.3 on 2025-08-05 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Texto'), ('choice', 'Selección'), ('number', 'Número'), ('date', 'Fecha'), ('file', 'Archivo')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('branch_to', models.ForeignKey(blank=True, help_text='Pregunta destino para ramificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.question')),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.questionnaire'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_fase', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_conductor', models.CharField(blank=True, max_length=100, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('answer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.submission')),
            ],
            options={
                'db_table': 'answer',
                'ordering': ['timestamp'],
            },
        ),
    ]
