# Generated by Django 5.0.3 on 2025-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_submission_fecha_cierre_submission_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_mode',
            field=models.CharField(blank=True, choices=[('image_only', 'Solo imagen'), ('image_ocr', 'Imagen + OCR')], default='image_only', max_length=20),
        ),
    ]
