# Generated by Django 5.0.3 on 2025-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_file_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='regulador_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
