# Generated by Django 5.0.3 on 2025-08-12 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_submission_regulador_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='question',
            name='file_mode',
            field=models.CharField(blank=True, choices=[('image_only', 'Solo imagen'), ('image_ocr', 'Imagen + OCR'), ('ocr_only', 'Solo OCR (requiere texto extraído)')], default='image_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='placa_vehiculo',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'order')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission', 'question'], name='answer_submiss_7a61b9_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['timestamp'], name='answer_timesta_d2956c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['finalizado', 'tipo_fase'], name='submission_finaliz_9159df_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tipo_fase', 'fecha_cierre'], name='submission_tipo_fa_654a57_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(check=models.Q(('answer_text__isnull', False), ('answer_choice__isnull', False), ('answer_file__isnull', False), _connector='OR'), name='answer_has_some_value'),
        ),
        migrations.AlterModelTable(
            name='submission',
            table='submission',
        ),
    ]
