# Generated by Django 5.0.3 on 2025-08-13 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_actor_y_campos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actor',
            new_name='actor_tipo_15372b_idx',
            old_name='actor_tipo_nombre_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submission_regulad_3a9248_idx',
            old_name='sub_reg_fase_fin_idx',
        ),
        migrations.AlterField(
            model_name='actor',
            name='documento',
            field=models.CharField(blank=True, db_index=True, help_text='RUC/NIT u otro identificador si aplica', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='proveedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROVEEDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_proveedor', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='receptor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'RECEPTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_receptor', to='app.actor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='transportista',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TRANSPORTISTA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions_transportista', to='app.actor'),
        ),
    ]
