# Generated by Django 5.2 on 2025-10-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_actor_tipo_nombre_idx_actor_tipo_15372b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='answer_has_some_value',
        ),
    ]
